language: ruby
cache: bundler

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.1

gemfile:
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_60.gemfile

jobs:
  exclude:
  - rvm: 2.4.9
    gemfile: gemfiles/rails_60.gemfile
